// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Adapter from "../Adapter.res.js";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";

let connected = {
  contents: false
};

async function runSopsCmd(args) {
  return await $$Deno.Command.run("sops", args);
}

async function connect() {
  let match = await runSopsCmd(["--version"]);
  if (match[0] === 0) {
    connected.contents = true;
    return;
  } else {
    return Stdlib_Exn.raiseError("SOPS CLI not found");
  }
}

async function disconnect() {
  connected.contents = false;
}

async function isConnected() {
  return connected.contents;
}

async function decryptHandler(args) {
  let match = args["file"];
  let file = typeof match === "string" ? match : Stdlib_Exn.raiseError("file parameter is required");
  let match$1 = args["outputType"];
  let outputType = typeof match$1 === "string" ? match$1 : undefined;
  let cmdArgs = ["--decrypt"];
  if (outputType !== undefined) {
    cmdArgs.push(`--output-type=` + outputType);
  }
  cmdArgs.push(file);
  let match$2 = await runSopsCmd(cmdArgs);
  let stdout = match$2[1];
  if (match$2[0] !== 0) {
    return Stdlib_Exn.raiseError(match$2[2]);
  }
  try {
    return JSON.parse(stdout);
  } catch (exn) {
    return Object.fromEntries([[
        "content",
        stdout
      ]]);
  }
}

async function encryptHandler(args) {
  let match = args["file"];
  let file = typeof match === "string" ? match : Stdlib_Exn.raiseError("file parameter is required");
  let match$1 = args["inPlace"];
  let inPlace = match$1 === true;
  let cmdArgs = ["--encrypt"];
  if (inPlace) {
    cmdArgs.push("--in-place");
  }
  cmdArgs.push(file);
  let match$2 = await runSopsCmd(cmdArgs);
  return Object.fromEntries([
    [
      "success",
      match$2[0] === 0
    ],
    [
      "output",
      match$2[1]
    ],
    [
      "error",
      match$2[2]
    ]
  ]);
}

async function setHandler(args) {
  let match = args["file"];
  let file = typeof match === "string" ? match : Stdlib_Exn.raiseError("file parameter is required");
  let match$1 = args["key"];
  let key = typeof match$1 === "string" ? match$1 : Stdlib_Exn.raiseError("key parameter is required");
  let match$2 = args["value"];
  let value = typeof match$2 === "string" ? match$2 : Stdlib_Exn.raiseError("value parameter is required");
  let match$3 = await runSopsCmd([
    "--set",
    `["` + key + `"] "` + value + `"`,
    file
  ]);
  return Object.fromEntries([
    [
      "success",
      match$3[0] === 0
    ],
    [
      "key",
      key
    ],
    [
      "output",
      match$3[1]
    ],
    [
      "error",
      match$3[2]
    ]
  ]);
}

async function rotateHandler(args) {
  let match = args["file"];
  let file = typeof match === "string" ? match : Stdlib_Exn.raiseError("file parameter is required");
  let match$1 = await runSopsCmd([
    "--rotate",
    "--in-place",
    file
  ]);
  return Object.fromEntries([
    [
      "success",
      match$1[0] === 0
    ],
    [
      "output",
      match$1[1]
    ],
    [
      "error",
      match$1[2]
    ]
  ]);
}

async function metadataHandler(args) {
  let match = args["file"];
  let file = typeof match === "string" ? match : Stdlib_Exn.raiseError("file parameter is required");
  let match$1 = await runSopsCmd([
    "--decrypt",
    "--output-type=json",
    file
  ]);
  let stdout = match$1[1];
  if (match$1[0] !== 0) {
    return Stdlib_Exn.raiseError(match$1[2]);
  }
  try {
    let parsed = JSON.parse(stdout);
    let obj = Js_json.decodeObject(parsed);
    if (obj === undefined) {
      return parsed;
    }
    let sops = Js_dict.get(obj, "sops");
    if (sops !== undefined) {
      return sops;
    } else {
      return parsed;
    }
  } catch (exn) {
    return Object.fromEntries([[
        "raw",
        stdout
      ]]);
  }
}

async function updateKeysHandler(args) {
  let match = args["file"];
  let file = typeof match === "string" ? match : Stdlib_Exn.raiseError("file parameter is required");
  let match$1 = await runSopsCmd([
    "updatekeys",
    file
  ]);
  return Object.fromEntries([
    [
      "success",
      match$1[0] === 0
    ],
    [
      "output",
      match$1[1]
    ],
    [
      "error",
      match$1[2]
    ]
  ]);
}

async function versionHandler(_args) {
  let match = await runSopsCmd(["--version"]);
  return Object.fromEntries([
    [
      "success",
      match[0] === 0
    ],
    [
      "version",
      match[1].trim()
    ],
    [
      "error",
      match[2]
    ]
  ]);
}

let tools = Object.fromEntries([
  [
    "sops_decrypt",
    {
      description: "Decrypt a SOPS-encrypted file",
      params: Object.fromEntries([
        [
          "file",
          Adapter.stringParam("Path to encrypted file")
        ],
        [
          "outputType",
          Adapter.stringParam("Output format (json, yaml, dotenv, binary)")
        ]
      ]),
      handler: decryptHandler
    }
  ],
  [
    "sops_encrypt",
    {
      description: "Encrypt a file with SOPS",
      params: Object.fromEntries([
        [
          "file",
          Adapter.stringParam("Path to file to encrypt")
        ],
        [
          "inPlace",
          Adapter.boolParam("Encrypt in place")
        ]
      ]),
      handler: encryptHandler
    }
  ],
  [
    "sops_set",
    {
      description: "Set a value in encrypted file",
      params: Object.fromEntries([
        [
          "file",
          Adapter.stringParam("Path to encrypted file")
        ],
        [
          "key",
          Adapter.stringParam("Key path to set")
        ],
        [
          "value",
          Adapter.stringParam("Value to set")
        ]
      ]),
      handler: setHandler
    }
  ],
  [
    "sops_rotate",
    {
      description: "Rotate encryption keys",
      params: Object.fromEntries([[
          "file",
          Adapter.stringParam("Path to encrypted file")
        ]]),
      handler: rotateHandler
    }
  ],
  [
    "sops_metadata",
    {
      description: "Get SOPS metadata from file",
      params: Object.fromEntries([[
          "file",
          Adapter.stringParam("Path to encrypted file")
        ]]),
      handler: metadataHandler
    }
  ],
  [
    "sops_updatekeys",
    {
      description: "Update keys for a file",
      params: Object.fromEntries([[
          "file",
          Adapter.stringParam("Path to encrypted file")
        ]]),
      handler: updateKeysHandler
    }
  ],
  [
    "sops_version",
    {
      description: "Show SOPS version",
      params: {},
      handler: versionHandler
    }
  ]
]);

let name = "sops";

let description = "Mozilla SOPS encrypted secrets";

export {
  connected,
  name,
  description,
  runSopsCmd,
  connect,
  disconnect,
  isConnected,
  decryptHandler,
  encryptHandler,
  setHandler,
  rotateHandler,
  metadataHandler,
  updateKeysHandler,
  versionHandler,
  tools,
}
/* tools Not a pure module */
