// Generated by ReScript, PLEASE EDIT WITH CARE


function getWithDefault(key, $$default) {
  let v = Deno.env.get(key);
  if (v !== undefined) {
    return v;
  } else {
    return $$default;
  }
}

let Env = {
  getWithDefault: getWithDefault
};

async function run(binary, args) {
  let cmd = new (Deno.Command)(binary, {
    args: args,
    stdout: "piped",
    stderr: "piped"
  });
  let result = await cmd.output();
  let decoder = new TextDecoder();
  return [
    result.code,
    decoder.decode(result.stdout),
    decoder.decode(result.stderr)
  ];
}

let Command = {
  run: run
};

export {
  Env,
  Command,
}
/* No side effect */
